# 该配置文件仅存放本地开发环境的配置项，默认情况下在线上环境会失效
# 通常来说，线上环境需要全量复制此配置文件内的配置节并进行调整
spring:
  servlet:
    multipart:
      max-file-size: 10240MB
      max-request-size: 10240MB
  redis:
    host: localhost
    port: 6379
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1.0.0
sup:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://seak8sm1.supcon5t.com:31230/tpt_recommend?characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: postgres
    password: Supcon@1304
  log:
    addr: http://localhost:8080
    remote:
      enabled: false
  schedule:
    username: admin
    password: 123456
    addresses: system-schedule-obp-dev.supcon5t.com/xxl-job-admin
    executor:
      address: http://10.30.75.78:9998
      appName: tpt-recommend-local
  tenant:
    dt: 0
    enabled: true
    db.enabled: true
    http.enabled: true
  websocket:
    # websocket 端点路径,多个中间','隔开
    path: /supWs
    session-key-options:
      # 是否开启key映射功能，默认关闭
      enabled: true
      # key类型：session绑定key，目前支持 user(用户)、param(参数) 两种模式，默认为none
      type: user
      # 全局消息开关，默认关闭
    globalSend: true

minio:
  endpoint: http://seak8sm1.supcon5t.com:30350
  accessKey: admin
  secretKey: Supcon1304
  bucket: recommend  #桶
feign:
  okhttp:
    enabled: true
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
    #打印SQL日志
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
service:
  llm:
    address: http://supcon-file-parsing-indu-dev.supcon5t.com
  dataHub:
    address: http://data-hub-obp-dev.supcon5t.com
  tempLabel:
    address: http://10.30.75.82:8080
  autoSupervision:
    address: http://auto-supervision-gpt-dev.supcon5t.com
  pid:
    address: http://obp-dev.supcon5t.com/xpt-tpt-pid/
  index:
    address: http://tpt-index-gpt-dev.supcon5t.com
  knowledge:
    address: http://supcon-rag-indu-dev.supcon5t.com
file:
  temp-dir: D:/temp/uploads
# 自定义线程池配置
threadpool:
  # 文件处理线程池配置
  file-processing:
    core-pool-size: 20       # 核心线程数 (建议与CPU核心数相同)
    max-pool-size: 40        # 最大线程数 (建议为CPU核心数的2倍)
    queue-capacity: 500      # 任务队列容量
    keep-alive-seconds: 60   # 线程空闲时间（秒）
    thread-name-prefix: "file-processor-" # 线程名前缀，便于日志排查
  file-upload:
    core-pool-size: 20       # 核心线程数 (建议与CPU核心数相同)
    max-pool-size: 30        # 最大线程数 (建议为CPU核心数的2倍)
    queue-capacity: 1000      # 任务队列容量
    keep-alive-seconds: 60   # 线程空闲时间（秒）
    thread-name-prefix: "file-upload-" # 线程名前缀，便于日志排查