server:
  port: 8088

spring:
  application:
    name: tpt-recommend

sup:
  swagger:
    api-base-package: "com.supcon"
    title: "tpt-recommend"
    description: "TptUserposApplication"
    version: "1.0.0-SNAPSHOT"

tpt:
  mq:
    file-parse-binding: tpt.recommend.file.parse
