server:
  port: 8088

spring:
  application:
    name: saas-file

sup:
  swagger:
    api-base-package: "com.example"
    title: "saas-file-manager"
    description: "Enterprise multi-tenant SaaS file management microservice"
    version: "0.1.0"

mq:
  file-parse-binding: saas.file.parse.parse
