# 该配置文件仅存放本地开发环境的配置项，默认情况下在线上环境会失效
# 通常来说，线上环境需要全量复制此配置文件内的配置节并进行调整
spring:
  servlet:
    multipart:
      max-file-size: 10240MB
      max-request-size: 10240MB
  redis:
    host: localhost
    port: 26379
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1.0.0
sup:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/saas-file?characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: app_user
    password: change_me
  log:
    addr: http://localhost:8080
    remote:
      enabled: false
  schedule:
    username: admin
    password: change_me
    addresses: localhost:8080/xxl-job-admin
    executor:
      address: http://127.0.0.1:9998
      appName: saas-file-manager
  tenant:
    dt: 0
    enabled: true
    db.enabled: true
    http.enabled: true
  websocket:
    # websocket 端点路径,多个中间','隔开
    path: /supWs
    session-key-options:
      # 是否开启key映射功能，默认关闭
      enabled: true
      # key类型：session绑定key，目前支持 user(用户)、param(参数) 两种模式，默认为none
      type: user
      # 全局消息开关，默认关闭
    globalSend: true

minio:
  endpoint: http://localhost:9000
  accessKey: minioadmin
  secretKey: change_me
  bucket: recommend  #桶
feign:
  okhttp:
    enabled: true
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
    #打印SQL日志
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
service:
  llm:
    address: http://localhost:18080
  dataHub:
    address: http://localhost:18081
  tempLabel:
    address: http://localhost:18082
  autoSupervision:
    address: http://localhost:18083
  pid:
    address: http://localhost:18084
  index:
    address: http://localhost:18085
  knowledge:
    address: http://localhost:18086
file:
  temp-dir: D:/temp/uploads
app:
  security:
    jwt-download-secret: "yXd3ecoPzJLfNvAI7Aq3ay9LPj4V2QxP9WSxJ1ZYDjt1i9gIkyUASsPd7rOOlpuPFeoeCirtvTjxJpbvVnuSaw=="




